# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: jira-lint
      # You may pin to the exact commit or the version.
      # uses: ClearTax/jira-lint@77705cbda2c5b24933e26534829d644b83ad3ae2
      uses: ClearTax/jira-lint@v0.0.1
      with:
        # Token used to update PR description and add labels. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # API Token used to access the JIRA REST API. Must have read access to your JIRA Projects & Issues.
        jira-token: ${{ secrets.JIRA_TOKEN }}
        # The subdomain of JIRA cloud that you use to access it. Ex: "https://your-domain.atlassian.net"
        jira-base-url: ${{ secrets.JIRA_URL }}
        # A regex to ignore running on certain branches, like production etc.
        skip-branches: "master"
